version: '3.8'
services:
  gorm_rest_api:
    build: ./
    ports: 
      - 8080:8080 
    environment: 
      - DB_PASSWORD=postgres
    depends_on:
      - db
    command: ./wait-for-postgres.sh db ./gorm_rest_api
    



  db:
    restart: always
    image: postgres:latest
    environment:  
      - POSTGRES_PASSWORD=postgres
    # volumes:
    #   - ./.database/postgres/data:/var/lib/postgresql/data 
    ports:
      - '5436:5432'
